-- +goose Up
-- OCR / ОГЗ tables (from firefight golang-migrate 0001+0002).
-- Without CREATE EXTENSION (managed-PG forbids). UUID generated by app.

CREATE TABLE IF NOT EXISTS jobs (
    id             uuid PRIMARY KEY,
    owner_sub      text        NOT NULL,
    status         text        NOT NULL,
    source_pdf_key text,
    error          text,
    confirmed      boolean     NOT NULL DEFAULT false,
    confirmed_at   timestamptz,
    created_at     timestamptz NOT NULL DEFAULT now(),
    updated_at     timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX IF NOT EXISTS idx_jobs_owner ON jobs (owner_sub);

CREATE TABLE IF NOT EXISTS recognition_rows (
    id             bigserial PRIMARY KEY,
    job_id         uuid    NOT NULL REFERENCES jobs (id) ON DELETE CASCADE,
    page           integer,
    raw_text       text,
    name           text,
    profile        text,
    mass           numeric(14, 3),
    mass_unit      text,
    is_sheet       boolean NOT NULL DEFAULT false,
    confidence     numeric(5, 4),
    construction   text,
    gost_profile   text,
    steel_grade    text,
    pp_number      text,
    total_mass     numeric(14, 3),
    created_at     timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX IF NOT EXISTS idx_recognition_rows_job ON recognition_rows (job_id);

CREATE TABLE IF NOT EXISTS ogz_rows (
    id                 bigserial PRIMARY KEY,
    job_id             uuid    NOT NULL REFERENCES jobs (id) ON DELETE CASCADE,
    recognition_row_id bigint  REFERENCES recognition_rows (id) ON DELETE SET NULL,
    name               text,
    profile_raw        text,
    profile_mark       text,
    mass               numeric(14, 3),
    mass_unit          text,
    mass_per_meter     numeric(14, 4),
    mass_source        text,
    is_sheet           boolean NOT NULL DEFAULT false,
    length_m           numeric(14, 2),
    area_m2            numeric(14, 2),
    classification     text,
    status             text    NOT NULL,
    heating_sides      text,
    fire_limit         text,
    bearing_type       text,
    coating_type       text,
    user_edited        boolean NOT NULL DEFAULT false,
    construction       text,
    gost_profile       text,
    steel_grade        text,
    pp_number          text,
    source_url         text,
    created_at         timestamptz NOT NULL DEFAULT now(),
    updated_at         timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX IF NOT EXISTS idx_ogz_rows_job ON ogz_rows (job_id);

CREATE TABLE IF NOT EXISTS profile_reference (
    id             bigserial PRIMARY KEY,
    mark           text          NOT NULL,
    mass_per_meter numeric(14, 4) NOT NULL,
    source         text          NOT NULL,
    owner_sub      text,
    created_at     timestamptz   NOT NULL DEFAULT now()
);
CREATE UNIQUE INDEX IF NOT EXISTS uq_profile_reference_mark_owner
    ON profile_reference (mark, COALESCE(owner_sub, ''));

CREATE TABLE IF NOT EXISTS audit (
    id         bigserial PRIMARY KEY,
    job_id     uuid REFERENCES jobs (id) ON DELETE CASCADE,
    owner_sub  text,
    action     text NOT NULL,
    details    jsonb,
    created_at timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX IF NOT EXISTS idx_audit_job ON audit (job_id);

-- +goose Down
DROP TABLE IF EXISTS audit;
DROP TABLE IF EXISTS profile_reference;
DROP TABLE IF EXISTS ogz_rows;
DROP TABLE IF EXISTS recognition_rows;
DROP TABLE IF EXISTS jobs;
